/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places within bbox and optional category */
        get: {
            parameters: {
                query: {
                    /** @description minLon,minLat,maxLon,maxLat */
                    bbox: string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Place"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get place by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Place"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a route between two points */
        get: {
            parameters: {
                query: {
                    mode: "walk" | "drive" | "transit";
                    /** @description lon,lat */
                    from: string;
                    /** @description lon,lat */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a review (moderated) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit data correction request (goes to moderation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GeoPoint: {
            lon: number;
            lat: number;
        };
        OpenHours: {
            [key: string]: unknown;
        };
        PriceInfo: {
            /** @example TRY */
            currency: string;
            amount: number;
        };
        Place: {
            id: string;
            name_tr: string;
            name_en?: string;
            category: string;
            geom: components["schemas"]["GeoPoint"];
            open_hours?: components["schemas"]["OpenHours"];
            price_info?: components["schemas"]["PriceInfo"];
        };
        RouteLeg: {
            distance_m: number;
            duration_s: number;
            geometry?: {
                /** @example LineString */
                type?: string;
                coordinates?: number[][];
            };
        };
        RouteResponse: {
            /** @enum {string} */
            mode: "walk" | "drive" | "transit";
            distance_m: number;
            duration_s: number;
            legs: components["schemas"]["RouteLeg"][];
        };
        ReviewInput: {
            placeId: string;
            rating: number;
            comment?: string;
        };
        Review: {
            id: string;
            placeId: string;
            rating: number;
            comment?: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            createdAt: string;
        };
        FeedbackInput: {
            placeId: string;
            /** @enum {string} */
            type: "hours" | "price" | "accessibility" | "metadata" | "other";
            payload: Record<string, never>;
            evidence?: {
                /** @enum {string} */
                kind?: "photo" | "url" | "text";
                url?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
